# Generated by Django 4.1.7 on 2024-04-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_users', models.IntegerField(default=25)),
                ('max_groups', models.IntegerField(default=5)),
                ('last_group', models.CharField(choices=[('LAST_MAX', 'Plus grand'), ('LAST_MIN', 'Plus petit')], default='LAST_MAX', max_length=8)),
                ('group_size', models.IntegerField(default=5)),
                ('last_group_size', models.IntegerField(default=5)),
            ],
        ),
    ]
