# Generated by Django 5.0.3 on 2024-04-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_users', models.IntegerField(default=25)),
                ('max_groups', models.IntegerField(default=5)),
                ('last_group', models.CharField(choices=[('LAST_MAX', 'Plus grand'), ('LAST_MIN', 'Plus petit')], max_length=8)),
            ],
        ),
    ]
